### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bamber123** [Pedramrn/CircularProgressBar#1]
Hi,

What license is this code available under?

By default, without a license, you retain all copyright, and other people cannot use, modify or create derivative works from your code.

If you do want people to be able to use your code in their projects, could you please choose [an appropriate open source license](http://choosealicense.com/) and add it to the README or to a LICENSE file so users can easily find it.

Thanks!

**Comment by MRezaNasirloo** [comment]
Hi,
I have added the license at the <a href="https://github.com/Pedramrn/CircularProgressBar/commit/68b7d47f2150abd590bac34d9468e4e0d0f9b5b0">second commit</a> as you see, but I will add the license to README file as soon as I can.
Thank you.

**Comment by bamber123** [comment]
Hi,
Great, I didn't spot that in the comments in each file!
Thanks!
