### ISSUE TITLE
Set radius of progressbar(Question)

### ISSUE THREAD

**Issue by norrisboat** [Pedramrn/CircularProgressBar#2]
Is there a way to set the radius of the the progress bar so it looks like the current material design progress bars. Something like this.
[Progress bar with radius](https://camo.githubusercontent.com/6ed028acbf67707d622344e0ef1bc3b098425b50/687474703a2f2f662e636c2e6c792f6974656d732f32473146315a304d306b306832553356317033392f535650726f67726573734855442e676966)

**Comment by MRezaNasirloo** [comment]
It's not an indeterminate progress bar, for practice you can write the code for achieving something like a material indeterminate progress bar, however there are loads of material design libraries which does this for you out of the box.

**Comment by norrisboat** [comment]
ok thanks
