### ISSUE TITLE
Initialize with countdown timer

### ISSUE THREAD

**Issue by TeodorKolev** [Pedramrn/CircularProgressBar#5]
I have initialize countdown time, but how to connect this CircleProgressBar with my countdown timer? How to start counting of timer? If I use setProgress animation is not smoot like examples.

**Comment by MRezaNasirloo** [comment]
Use [setProgressWithAnimation](https://github.com/Pedramrn/CircularProgressBar/blob/master/app/src/main/java/com/mrn/customprogressbar/CircleProgressBar.java#L199)

**Comment by TeodorKolev** [comment]
Hello, my target is to start from 30 seconds to 0. So circle must be backwards. I have used to trigger `circleProgressBar.setProgressWithAnimation(1000);` but this just fill it from start to end for one second.
Full code:
 ```
  @Override
    public void setCountdownTimer(int seconds) {
        CountDownTimer countDownTimer = new CountDownTimer(seconds * 1000, 1000) {
            @Override
            public void onTick(long leftTimeInMilliseconds) {
                long seconds = leftTimeInMilliseconds / 1000;
                circleProgressBar.setProgressWithAnimation(seconds);
            }
            @Override
            public void onFinish() {
                circleProgressBar.setProgress(0);
            }
        };
        countDownTimer.start();
    }
```

**Comment by MRezaNasirloo** [comment]
It does not intent to work like that, you have to add a method and use the the object animator api to animate the progress bar as the way you wanted, and abandon the ticker thing for this part.

**Comment by TeodorKolev** [comment]
OK, my question is that possible to achieve that result. 30 seconds start backwards, step - 1/30?

**Comment by MRezaNasirloo** [comment]
It won't be as smooth as the animation on stock android stopwatch.

**Comment by TeodorKolev** [comment]
So, I am unable to achieve that with setProgressWithAnimation?

**Comment by TeodorKolev** [comment]
My target is to achieve 30 seconds start from backwards, smooth

**Comment by MRezaNasirloo** [comment]
I'm afraid you cannot.
